### ISSUE TITLE
Canonical URL matching causes unexpected behaviour

### ISSUE THREAD

**Issue by brianbento** [wardpeet/gatsby-plugin-static-site#1]
I have an old site that I'm replacing with a Gatsby site. The issue is I'm hosting the gatsby site in a directory structure for the future state. To host the site in a subdirectory I'm using pathPrefix. 

EG. Current site = https://example.com
Gatsby site = https://examples.com/gatsby

The idea is to replace the old pages slowly by replacing the html with that generated by gatsby. This is done via edge side includes at the CDN level. So it's like an iframe but with no iframe.

EG. Gatsby URL: https://examples.com/gatsby/foo
Old URL that's being replaced: https://examples.com/foo

The problem is this check in production-app.js.

https://github.com/gatsbyjs/gatsby/blob/b9411d80691c7e6942b15053bbf2784fa22efec6/packages/gatsby/cache-dir/production-app.js#L68

```
if (
    // Make sure the window.page object is defined
    page &&
    // The canonical path doesn't match the actual path (i.e. the address bar)
    __PATH_PREFIX__ + page.path !== browserLoc.pathname &&
    // ...and if matchPage is specified, it also doesn't match the actual path
    (!page.matchPath ||
      !match(__PATH_PREFIX__ + page.matchPath, browserLoc.pathname)) &&
    // Ignore 404 pages, since we want to keep the same URL
    page.path !== `/404.html` &&
    !page.path.match(/^\/404\/?$/) &&
    // Also ignore the offline shell (since when using the offline plugin, all
    // pages have this canonical path)
    !page.path.match(/^\/offline-plugin-app-shell-fallback\/?$/)
  ) {
    navigate(
      __PATH_PREFIX__ + page.path + browserLoc.search + browserLoc.hash,
      { replace: true }
    )
  }
```
No matter how I try to short out this check I can't because __PATH_PREFIX__ is always called into every check.

The fix suggested below doesn't work as the path prefix (/gatsby) would not be included in window.location.pathname. Same issue happens with setting matchPath as the above check also add the path prefix in the check.
https://github.com/gatsbyjs/gatsby/issues/4337#issuecomment-453244611
```
window.page = window.page || {};
window.page.path = window.location.pathname;
```

I just need to have the canonical check not happen and let me host any gatsby page into any other location no matter the pathname.

**Comment by xavivars** [comment]
I'm facing the same problem than @brianbento. I'd love to have a way to fully disable that conditional check

**Comment by xavivars** [comment]
@wardpeet: this is also what I had to add to make it fully work: in gatsby-browser

    exports.onClientEntry = () => {
        window.page = window.page || {};
        window.page.path = window.location.pathname;
    }

Should this be added somehow to the plugin?

**Comment by wardpeet** [comment]
Let me have a look next week as I'm currently in New York with the gatsby team

**Comment by brianbento** [comment]
@xavivars I'm actually having the path being updated before onClientEntry fires. By the time the code has loaded it path has already been changes to the one that gatsby expects.

The proposed fix actually causes the pathname to be duplicated.

https://example.com/foo becomes https://example.com/foo/foo

Also

https://example.com/foo/bar becomes https://example.com/foo/foo/bar

**Comment by xavivars** [comment]
I'm actually using it without a path now, but with an assetPrefix, and that works. Didn't try with path, but I guess you should be removing basepath from this so it doesn't get added twice `window.page.path = window.location.pathname;`

**Comment by wardpeet** [comment]
I could fix this when adding `assetPrefix: '/foo'` to your gatsby-config.js

more info:
https://www.gatsbyjs.org/docs/asset-prefix/

This way your html files can live at / but your assets will live in /foo

**Comment by xavivars** [comment]
Maybe overriding `match` from `"@reach/router/lib/utils"` to always match could be a way to disable the the canonical redirect check... (but match is used also in the `gatsby serve` command, not sure if this plugin only affects build and not develop

**Comment by wardpeet** [comment]
overriding utils wouldn't fix page-data requests.

I have a PR up that should fix this.
A demo: (page 5 has a canonical redirect)
https://static-asset-prefix--zen-wright-33c2d8.netlify.com

**Comment by wardpeet** [comment]
I've published a new minor `@wardpeet/gatsby-plugin-static-site 0.1.0`. Please note that the minimum gatsby version is 2.11.1.

I'll be closing this issue, please reopen if it hasn't been resolved.
