### ISSUE TITLE
Question: Multiple pages mapping to same url

### ISSUE THREAD

**Issue by ethannkschneider** [wardpeet/gatsby-plugin-static-site#12]
Hello! I came across this plugin after searching through various github and SO posts. I'm a bit unclear on the ideal use case for this, so I wanted to ask the following:

I have a Gatsby site that sits behind another app (say example.com). This other app handles all the routing;  if a user goes to example.com/gatsby/page-one, this other app forwards the request to my app (since it has the 'gatsby' prefix), and adds some headers to the request as well. I would like my app to serve different pages based on the value of these headers.

For instance, I recently redesigned my app, and now have two versions of each page generated at build time -- one with the old design, one with the new. If there is a request to my app with a header specifying to use the old design, I want to serve the page 'gatsby/page-one-old-design'. Similarly, if the header says to use the new design, I want to serve 'gatsby/page-one-new-design'. However, I run into a variety of issues when the pagePath of the Gatsby page I serve doesn't match the url in the browser (unwanted redirects, etc).

Is this a valid use case for this plugin? If not, do you have any suggestions on how to accomplish this?

Thanks, and apologies if this is the wrong place to ask!

**Comment by wardpeet** [comment]
Hey, this plugin allows you to use url rewrite rules and/or a proxy server. So it should be possible for what you ask for.

A simple demo can be found here: https://gatsby-static-site-demo.netlify.com/. This show a non gatsby-site loading a gatsby-site on the same domain.
