### ISSUE TITLE
Breaks site in IE11

### ISSUE THREAD

**Issue by brianbento** [wardpeet/gatsby-plugin-static-site#32]
Updated to the latest version of Gatsby and this plugin and noticed the site stopped working in IE11.

After some sleuthing, I found that removing the static-site plugin fixed the issue.

Live error can be seen @ https://quickbooks.intuit.com/ca.

Image of error:
<img width="483" alt="Screen Shot 2020-01-31 at 9 45 59 PM" src="https://user-images.githubusercontent.com/679069/73614255-685fae00-45cb-11ea-8e40-d7f509277a26.png">

Where it leads too:
<img width="511" alt="Screen Shot 2020-01-31 at 9 46 25 PM" src="https://user-images.githubusercontent.com/679069/73614259-6dbcf880-45cb-11ea-8e08-186c63a06712.png">

**Comment by brianbento** [comment]
I've had success ripping the code out of the plugin and placing it directly into `gatsby-node.js` and `gatsby-browser.js`.

**Comment by brianbento** [comment]
Bump

**Comment by LewisYearsley** [comment]
@brianbento had this same issue. Submitted a PR for it at https://github.com/wardpeet/gatsby-plugin-static-site/pull/35

**Comment by wardpeet** [comment]
Oh I'm sorry, I missed this. I'll have a look at the PR

**Comment by LucyMac** [comment]
Having the same issue here @wardpeet - thanks 🙂

**Comment by LewisYearsley** [comment]
Tested the latest version from NPM (0.2.3) now that the PR has been merged and verified that, in my case, the problem is solved and IE11 is working again! 🎉 

FYI @brianbento @LucyMac

**Comment by LucyMac** [comment]
This has fixed everything that was broken on IE11! Thank you @LewisYearsley and @wardpeet <3

**Comment by brianbento** [comment]
I'd say it's safe to mark this closed. Thanks @wardpeet and @LewisYearsley!
