### ISSUE TITLE
Router override is not bundled by webpack

### ISSUE THREAD

**Issue by xavivars** [wardpeet/gatsby-plugin-static-site#5]
For some reason, when using the plugin, the override of `@reach/router` is not getting bundled by webpack.

This repo gatsby starter + plugin
https://github.com/xavivars/gatsbybug

and it's deployed here and doesn't work: 
http://gatsby-bug.s3-website-eu-west-1.amazonaws.com/notworking/page-2/

(you will see a redirect happening)

I can't understand why it works in here

http://gatsby-bug.s3-website-eu-west-1.amazonaws.com/gatsby/page-3/

(source code for this is coming from https://github.com/wardpeet/gatsby-demos/tree/static-asset-prefix )

**Comment by xavivars** [comment]
It seems it has to do with webpack prefering `es` version of `@reach/router` instead of the `commonjs` version, so then the webpack override (the one that looks for `@reach/router` usages) never gets applied.

I'm not sure if this has something to do with https://github.com/gatsbyjs/gatsby/pull/15270

**Comment by xavivars** [comment]
Should we need https://github.com/gatsbyjs/gatsby/blob/master/packages/babel-preset-gatsby?

**Comment by xavivars** [comment]
Closing, as I can't reproduce it anymore...

If the issue re-appears, I'll re-open it.

**Comment by xavivars** [comment]
I think I know why this is happening...

https://github.com/gatsbyjs/gatsby/pull/13197/files/931c911c59f876639b0cfddfd5a5a1a5acc2f1b4#diff-c4777e791f64fbb6c82255341b381dabR374

**Comment by xavivars** [comment]
@wardpeet, any chance to look into this?

**Comment by wardpeet** [comment]
Hey sorry, i'll try to get to it somewhere this week, it has been a few busy weeks and I went on vacation.

**Comment by apaniel** [comment]
update on why the page goes blank:
https://github.com/wardpeet/gatsby-plugin-static-site/issues/10#issuecomment-528752467

**Comment by wardpeet** [comment]
Sorry for my absence, I haven't read through the issue yet but I'll make sure that it works again this week, I hope to get a new release out tomorrow or the day after.

**Comment by xavivars** [comment]
Temporarily, while #9 and #11 get merged I've published a _fork_ of this plug-in with both PRs merged as https://www.npmjs.com/package/@xavivars/gatsby-plugin-static-site

**Comment by fodkastir** [comment]
@xavivars Thanks for publishing your fork. Could you recommend a specific version of Gatsby that works with your fork? Thanks again.
