### ISSUE TITLE
Plugin not compatible with gatsby V3

### ISSUE THREAD

**Issue by edmarval** [wardpeet/gatsby-plugin-static-site#57]

**Comment by artmsv** [comment]
Same here, doesn't work with gatsby@3

**Comment by simplenotezy** [comment]
Same

**Comment by wardpeet** [comment]
I'll update it and release a new major. Thanks for notifying

**Comment by JimCaignard** [comment]
@wardpeet Any news on the update ? :)

**Comment by JimCaignard** [comment]
If anyone need it, i found a fork where the problem was solve : [https://github.com/redabacha/gatsby-plugin-static-site]
It works with gatsby V3 ;)

**Comment by xavivars** [comment]
@JimCaignard, thanks for sharing. I went ahead and made a PR, so @wardpeet can take a look at it, and see if it can be merged.

**Comment by redabacha** [comment]
yes i made the fix for gatsby v3 but i didn't make any effort to fix the tests as i was looking for a quick solution at the time. i've made a pr here to remedy that: https://github.com/wardpeet/gatsby-plugin-static-site/pull/60

**Comment by xavivars** [comment]
Thanks @redabacha! I closed mine (I was actually trying to fix it myself, but if you had it done, that's even better :)

**Comment by wardpeet** [comment]
Thanks for waiting, I was a bit busy with life. Publishing a new major right now.
